name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Ubuntu 20.04
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libjavascriptcoregtk-4.0-dev \
            libsoup2.4-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libglib2.0-dev \
            pkg-config \
            build-essential

      - name: Install Node dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        run: npm run tauri:build -- --bundles deb

      - name: List generated files
        run: |
          echo "Generated files:"
          ls -lh src-tauri/target/release/bundle/deb/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecolav-totem-ubuntu-20.04
          path: src-tauri/target/release/bundle/deb/*.deb
          retention-days: 30
