name: Tauri Build (Windows & Linux)

on:
  push:
    branches: [ main ]
    tags: [ 'v*', 'release-*' ]
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            bundles: deb,appimage,rpm
          - os: windows-latest
            bundles: nsis

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libjavascriptcoregtk-4.0-dev \
            libsoup2.4-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libglib2.0-dev \
            libgirepository1.0-dev \
            pkg-config \
            build-essential \
            curl wget file patchelf rpm

      - name: Install JS deps
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Tauri build
        run: npx tauri build --bundles ${{ matrix.bundles }}

      - name: Upload bundles
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundles-${{ runner.os }}
          path: |
            src-tauri/target/release/bundle/**
          if-no-files-found: error


